services:
    - docker

before_install:
    - docker build -t dockertest .

script:
    # installed lib check
    - docker run dockertest mkdocs --version
    - docker run dockertest weasyprint --version
    # build mkdocs
    # build with mkdocs
