site_name: Extended MkDocs Docker
theme:
  name: 'material'
  palette:
    primary: 'Teal'
    accent: 'indigo'
  logo:
    icon: 'extension'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - sane_lists
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - plantuml_markdown
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

plugins:
    - search
    - pdf-export:
        combined: true
        combined_output_path: ../pdf/combined.pdf
        enabled_if_env: ENABLE_PDF_EXPORT
